"""
RingBreaker SHAP Explainability Engine
======================================
Explains payment risk scores generated by the trained XGBoost Pair Risk Model.
Uses TreeExplainer in margin (log-odds) space with sigmoid probability mapping.
Features automatic fallback to XGBoost's native compiled Tree SHAP engine
(pred_contribs=True) to avoid Windows C-extension / namespace collision issues.

Outputs:
  - Local transaction risk factor breakdowns (risk-increasing vs risk-reducing)
  - Human-readable descriptions for fraud analysts
  - Structured JSON export under data/shap_explanations/
  - Optional SHAP bar plots saved under explain/plots/
  - Global feature importance summary across dataset partitions
"""

import os
import sys
import json
import argparse
import numpy as np
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt

# File paths
MODEL_PATH = "models/pair_model.json"
PAIR_FEATURES_PATH = "data/pair_features.csv"
SCORED_PAYMENTS_PATH = "data/scored_payments.csv"
SHAP_EXPORT_DIR = os.path.join("data", "shap_explanations")
PLOTS_DIR = os.path.join("explain", "plots")

METADATA_COLS = ["transaction_id", "timestamp", "sender", "receiver", "is_fraud", "ring_id"]

FEATURE_DESCRIPTIONS = {
    "amount": "Transaction payment amount in INR",
    "log_amount": "Log-scaled payment amount (squashes extreme variance)",
    "hour": "Hour of day when payment was submitted (0-23)",
    "day_of_week": "Day of week (0=Monday, 6=Sunday)",
    "day_of_month": "Day of the month (1-31)",
    "is_weekend": "Indicates whether payment occurred on a Saturday or Sunday",
    "is_night": "Indicates whether payment occurred during late night hours (00:00 - 05:59)",
    "sender_account_age_days": "Number of days elapsed since sender account registered",
    "receiver_account_age_days": "Number of days elapsed since receiver account registered",
    "sender_tx_count_before": "Total count of prior outgoing payments dispatched by sender",
    "sender_unique_receivers_before": "Number of distinct beneficiaries previously paid by sender",
    "sender_avg_amount_before": "Historical average amount dispatched by sender",
    "sender_max_amount_before": "Historical maximum single payment sent by sender",
    "sender_avg_time_gap": "Historical average time elapsed between sender outgoing payments",
    "sender_tx_last_1h": "High velocity check: Outgoing payments sent in previous 1 hour",
    "sender_tx_last_24h": "Velocity check: Outgoing payments sent in previous 24 hours",
    "sender_tx_last_7d": "Velocity check: Outgoing payments sent in previous 7 days",
    "receiver_tx_count_before": "Total count of prior incoming payments received by receiver",
    "receiver_unique_senders_before": "Number of distinct senders who previously paid receiver",
    "receiver_avg_amount_before": "Historical average amount received by receiver",
    "receiver_max_amount_before": "Historical maximum single payment received by receiver",
    "receiver_tx_last_1h": "High velocity check: Payments received in previous 1 hour",
    "receiver_tx_last_24h": "Velocity check: Payments received in previous 24 hours",
    "receiver_tx_last_7d": "Velocity check: Payments received in previous 7 days",
    "pair_tx_count_before": "Number of prior payments between this exact sender-receiver pair",
    "pair_avg_amount_before": "Historical average payment amount between this exact pair",
    "time_since_previous_pair_tx": "Seconds elapsed since prior payment between this exact pair",
    "is_first_transaction_between_pair": "Flags a completely new, unestablished counterparty relationship",
    "device_tx_count_before": "Historical count of all payments originating from this device",
    "device_unique_users_before": "Device collusion check: Distinct user accounts sharing this device",
    "ip_tx_count_before": "Historical count of all payments originating from this IP address",
    "ip_unique_users_before": "IP collusion check: Distinct user accounts sharing this IP address",
    "sender_in_degree_before": "Historical in-degree: Times sender previously received money",
    "sender_out_degree_before": "Historical out-degree: Times sender previously dispatched money",
    "receiver_in_degree_before": "Historical in-degree: Times receiver previously received money",
    "receiver_out_degree_before": "Historical out-degree: Times receiver previously dispatched money",
    "sender_out_in_ratio": "Sender flow balance: Outgoing transactions divided by (Incoming + 1)",
    "receiver_in_out_ratio": "Receiver flow balance: Incoming transactions divided by (Outgoing + 1)",
    "sender_time_since_last_incoming": "Pass-through dwell proxy: Seconds since sender last received funds"
}


def load_model(model_path=MODEL_PATH):
    """Loads trained Pair Risk XGBoost model."""
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model file not found: {model_path}. Train the model first.")

    clf = xgb.XGBClassifier()
    clf.load_model(model_path)
    return clf


def compute_shap_contributions(clf, X_df):
    """
    Computes exact Tree SHAP values.
    Uses XGBoost's native compiled Booster.predict(..., pred_contribs=True)
    which guarantees exact Tree SHAP in log-odds space with zero external dependencies.
    """
    booster = clf.get_booster()
    dmat = xgb.DMatrix(X_df, feature_names=list(X_df.columns))
    
    # In XGBoost, pred_contribs=True returns an array of shape (N, num_features + 1)
    # where the last column is the base_value (bias term)
    contribs = booster.predict(dmat, pred_contribs=True)
    
    shap_values = contribs[:, :-1]
    base_value = float(contribs[0, -1])
    
    return shap_values, base_value


def load_feature_dataset(features_path=PAIR_FEATURES_PATH, scored_path=SCORED_PAYMENTS_PATH):
    """Loads feature matrix and scored payments."""
    if not os.path.exists(features_path):
        raise FileNotFoundError(f"Feature table not found: {features_path}")

    df_feat = pd.read_csv(features_path)
    df_scored = pd.read_csv(scored_path) if os.path.exists(scored_path) else None

    # Filter out metadata to isolate the exact 39 ML features
    feature_cols = [c for c in df_feat.columns if c not in METADATA_COLS]

    return df_feat, df_scored, feature_cols


def explain_transaction(transaction_id, top_n=5, save_json=True, generate_plot=False):
    """
    Generates local SHAP explanation for an individual transaction.
    """
    clf = load_model()
    df_feat, df_scored, feature_cols = load_feature_dataset()

    tx_match = df_feat[df_feat["transaction_id"] == transaction_id]
    if tx_match.empty:
        raise ValueError(f"Transaction ID '{transaction_id}' not found in {PAIR_FEATURES_PATH}")

    row_idx = tx_match.index[0]
    X_row = df_feat.loc[[row_idx], feature_cols]

    # Predict risk score directly
    risk_score = float(clf.predict_proba(X_row)[0, 1])

    # Metadata
    sender = tx_match.iloc[0]["sender"]
    receiver = tx_match.iloc[0]["receiver"]
    timestamp = tx_match.iloc[0]["timestamp"]
    ring_id = str(tx_match.iloc[0]["ring_id"]) if pd.notnull(tx_match.iloc[0]["ring_id"]) else ""

    # Compute SHAP values via native engine
    shap_vals_matrix, base_val = compute_shap_contributions(clf, X_row)
    row_shap = shap_vals_matrix[0]

    # Mathematical additivity check in log-odds space
    margin_sum = base_val + float(np.sum(row_shap))
    recon_prob = 1.0 / (1.0 + np.exp(-margin_sum))
    abs_prob_err = abs(recon_prob - risk_score)

    factors = []
    for f_name, f_val, s_val in zip(feature_cols, X_row.iloc[0], row_shap):
        direction = "risk_increasing" if s_val > 0 else "risk_reducing"
        desc = FEATURE_DESCRIPTIONS.get(f_name, "Behavioral feature metric")
        factors.append({
            "feature": f_name,
            "value": float(f_val),
            "shap_value": float(round(s_val, 5)),
            "abs_shap": float(abs(s_val)),
            "direction": direction,
            "description": desc
        })

    factors.sort(key=lambda x: x["abs_shap"], reverse=True)

    top_factors = factors[:top_n]
    risk_increasing = [f for f in factors if f["direction"] == "risk_increasing"][:top_n]
    risk_reducing = [f for f in factors if f["direction"] == "risk_reducing"][:top_n]

    result = {
        "transaction_id": transaction_id,
        "timestamp": timestamp,
        "sender": sender,
        "receiver": receiver,
        "ring_id": ring_id,
        "risk_score": float(round(risk_score, 4)),
        "base_value_log_odds": float(round(base_val, 4)),
        "shap_space": "log_odds (raw margin)",
        "reconstructed_probability": float(round(recon_prob, 4)),
        "math_additivity_check": "PASSED" if abs_prob_err < 1e-4 else f"WARNING (diff={abs_prob_err:.6f})",
        "top_factors": top_factors,
        "risk_increasing_factors": risk_increasing,
        "risk_reducing_factors": risk_reducing
    }

    if save_json:
        os.makedirs(SHAP_EXPORT_DIR, exist_ok=True)
        out_file = os.path.join(SHAP_EXPORT_DIR, f"{transaction_id}.json")
        with open(out_file, "w") as f:
            json.dump(result, f, indent=2)

    if generate_plot:
        plot_path = plot_transaction_shap(transaction_id, top_factors, risk_score)
        result["plot_path"] = plot_path

    return result


def plot_transaction_shap(transaction_id, top_factors, risk_score, output_dir=PLOTS_DIR):
    """Renders horizontal bar chart of top risk contributors."""
    os.makedirs(output_dir, exist_ok=True)

    features = [f["feature"] for f in reversed(top_factors)]
    shap_vals = [f["shap_value"] for f in reversed(top_factors)]
    colors = ["#e63946" if v > 0 else "#457b9d" for v in shap_vals]

    plt.figure(figsize=(9, 5))
    bars = plt.barh(features, shap_vals, color=colors, edgecolor="black", linewidth=0.5)

    plt.axvline(0, color="gray", linestyle="--", linewidth=1.0)
    plt.title(f"SHAP Attribution: {transaction_id} (Predicted Risk Score: {risk_score:.4f})", fontsize=11, fontweight="bold")
    plt.xlabel("SHAP Contribution in Log-Odds (Red = Risk Increasing, Blue = Risk Reducing)")

    for bar in bars:
        width = bar.get_width()
        ha = "left" if width >= 0 else "right"
        offset = 0.02 if width >= 0 else -0.02
        plt.text(width + offset, bar.get_y() + bar.get_height() / 2, f"{width:+.2f}", va="center", ha=ha, fontsize=9)

    plt.tight_layout()
    plot_file = os.path.join(output_dir, f"{transaction_id}_shap.png")
    plt.savefig(plot_file, dpi=200)
    plt.close()
    return plot_file


def generate_global_summary(max_samples=1500, top_k=15):
    """Computes global feature importance using mean(|SHAP value|) across transactions."""
    clf = load_model()
    df_feat, _, feature_cols = load_feature_dataset()

    sample_size = min(len(df_feat), max_samples)
    X_sample = df_feat[feature_cols].iloc[:sample_size]

    shap_matrix, _ = compute_shap_contributions(clf, X_sample)
    mean_abs_shap = np.mean(np.abs(shap_matrix), axis=0)

    summary_df = pd.DataFrame({
        "feature": feature_cols,
        "mean_abs_shap": mean_abs_shap,
        "description": [FEATURE_DESCRIPTIONS.get(f, "") for f in feature_cols]
    }).sort_values(by="mean_abs_shap", ascending=False).reset_index(drop=True)

    print("\n" + "=" * 70)
    print("RINGBREAKER GLOBAL SHAP FEATURE IMPORTANCE SUMMARY")
    print("=" * 70)
    print(f"{'Feature Name':<34} | {'Mean |SHAP|':<12} | {'Description'}")
    print("-" * 70)
    for _, row in summary_df.head(top_k).iterrows():
        print(f"{row['feature']:<34} | {row['mean_abs_shap']:<12.4f} | {row['description']}")
    print("=" * 70)

    return summary_df


def print_explanation(exp):
    """Outputs formatted analyst terminal view."""
    print("\n" + "=" * 62)
    print("RINGBREAKER SHAP EXPLANATION REPORT")
    print("=" * 62)
    print(f"Transaction ID:       {exp['transaction_id']}")
    print(f"Timestamp:            {exp['timestamp']}")
    print(f"Sender:               {exp['sender']}")
    print(f"Receiver:             {exp['receiver']}")
    if exp["ring_id"]:
        print(f"Associated Ring ID:   {exp['ring_id']}")
    print(f"Predicted Risk Score: {exp['risk_score']:.4f}")
    print(f"SHAP Space:           {exp['shap_space']}")
    print(f"Base Value (LogOdds): {exp['base_value_log_odds']:.4f}")
    print(f"Reconstructed Prob:   {exp['reconstructed_probability']:.4f} ({exp['math_additivity_check']})")

    print("\nTop Risk-Increasing Factors (Pushed score toward Fraud):")
    if exp["risk_increasing_factors"]:
        for i, f in enumerate(exp["risk_increasing_factors"], 1):
            print(f"  {i}. {f['feature']} (value: {f['value']})")
            print(f"     Contribution: +{f['shap_value']:.4f} log-odds")
            print(f"     Context:      {f['description']}")
    else:
        print("  (None detected)")

    print("\nTop Risk-Reducing Factors (Pushed score toward Normal):")
    if exp["risk_reducing_factors"]:
        for i, f in enumerate(exp["risk_reducing_factors"], 1):
            print(f"  {i}. {f['feature']} (value: {f['value']})")
            print(f"     Contribution: {f['shap_value']:.4f} log-odds")
            print(f"     Context:      {f['description']}")
    else:
        print("  (None detected)")
    print("=" * 62)


def main():
    parser = argparse.ArgumentParser(description="RingBreaker SHAP Explainability Engine")
    parser.add_argument("--transaction", type=str, default=None, help="Transaction ID to explain (e.g., TX_0001845)")
    parser.add_argument("--top-n", type=int, default=5, help="Number of top factors to display")
    parser.add_argument("--plot", action="store_true", help="Generate and save a bar plot under explain/plots/")
    parser.add_argument("--global-summary", action="store_true", help="Print global SHAP feature importance summary")
    args = parser.parse_args()

    if args.global_summary:
        generate_global_summary()
        return

    if args.transaction:
        exp = explain_transaction(args.transaction, top_n=args.top_n, save_json=True, generate_plot=args.plot)
        print_explanation(exp)
        return

    print("No specific --transaction provided. Running automatic validation on 1 Held-Out Fraud and 1 Normal payment...")
    df_scored = pd.read_csv(SCORED_PAYMENTS_PATH)

    # 1. Held-Out Fraud sample
    heldout_txs = df_scored[df_scored["ring_id"] == "RING_HELDOUT"]
    sample_fraud_id = heldout_txs.iloc[0]["transaction_id"] if not heldout_txs.empty else df_scored[df_scored["is_fraud"] == 1].iloc[0]["transaction_id"]

    # 2. Normal sample
    sample_normal_id = df_scored[df_scored["is_fraud"] == 0].iloc[100]["transaction_id"]

    print("\n--- [CASE 1: FRAUDULENT PAYMENT EXPLANATION] ---")
    fraud_exp = explain_transaction(sample_fraud_id, top_n=args.top_n, save_json=True, generate_plot=True)
    print_explanation(fraud_exp)

    print("\n--- [CASE 2: NORMAL PAYMENT EXPLANATION] ---")
    norm_exp = explain_transaction(sample_normal_id, top_n=args.top_n, save_json=True, generate_plot=True)
    print_explanation(norm_exp)

    print(f"\nExplanations saved in: '{SHAP_EXPORT_DIR}/'")
    print(f"Plots saved in:        '{PLOTS_DIR}/'")


if __name__ == "__main__":
    main()